In [9]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import copy

from sklearn.preprocessing import StandardScaler

In [3]:
data = pd.read_csv("Iris.csv")

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [15]:
df = copy.deepcopy(data)

In [16]:
df.describe().T

               count       mean        std  min    25%    50%     75%    max
Id             150.0  75.500000  43.445368  1.0  38.25  75.50  112.75  150.0
SepalLengthCm  150.0   5.843333   0.828066  4.3   5.10   5.80    6.40    7.9
SepalWidthCm   150.0   3.054000   0.433594  2.0   2.80   3.00    3.30    4.4
PetalLengthCm  150.0   3.758667   1.764420  1.0   1.60   4.35    5.10    6.9
PetalWidthCm   150.0   1.198667   0.763161  0.1   0.30   1.30    1.80    2.5

In [17]:
df.drop(columns=['Id', 'Species'], inplace=True)

In [18]:
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0              5.1           3.5            1.4           0.2
1              4.9           3.0            1.4           0.2
2              4.7           3.2            1.3           0.2
3              4.6           3.1            1.5           0.2
4              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
145            6.7           3.0            5.2           2.3
146            6.3           2.5            5.0           1.9
147            6.5           3.0            5.2           2.0
148            6.2           3.4            5.4           2.3
149            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

## Scaling

In [20]:
s = StandardScaler()

column_names = df.columns
index_names = df.index
s = StandardScaler()
df_ = s.fit_transform(df)
df_scaled = pd.DataFrame(df_, index=index_names, columns=column_names)

In [21]:
df_scaled

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0        -0.900681      1.032057      -1.341272     -1.312977
1        -1.143017     -0.124958      -1.341272     -1.312977
2        -1.385353      0.337848      -1.398138     -1.312977
3        -1.506521      0.106445      -1.284407     -1.312977
4        -1.021849      1.263460      -1.341272     -1.312977
..             ...           ...            ...           ...
145       1.038005     -0.124958       0.819624      1.447956
146       0.553333     -1.281972       0.705893      0.922064
147       0.795669     -0.124958       0.819624      1.053537
148       0.432165      0.800654       0.933356      1.447956
149       0.068662     -0.124958       0.762759      0.790591

[150 rows x 4 columns]

## Clustering

### KMeans

In [22]:
from sklearn.cluster import KMeans

k_means = KMeans(n_clusters=3, n_init=10)
k_means.fit(df_scaled)

KMeans(n_clusters=3, n_init=10)

In [23]:
k_means.labels_

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0], dtype=int32)

### Hierarchical Clustering

In [24]:
from sklearn.cluster import AgglomerativeClustering

hc = AgglomerativeClustering(n_clusters=3, metric="euclidean", linkage="ward")
hc_cluster = hc.fit_predict(df_scaled)

In [25]:
hc_cluster

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 2, 0, 2, 0, 2, 0, 2, 2, 0, 2, 0, 2, 0,
       2, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 0, 2, 0, 0, 2,
       2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Meaning of numbers

In [43]:
data['kmeans'] = k_means.labels_

In [32]:
data[data['kmeans'] == 2]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,kmeans
0,1,5.1,3.5,1.4,0.2,Iris-setosa,2
1,2,4.9,3.0,1.4,0.2,Iris-setosa,2
2,3,4.7,3.2,1.3,0.2,Iris-setosa,2
3,4,4.6,3.1,1.5,0.2,Iris-setosa,2
4,5,5.0,3.6,1.4,0.2,Iris-setosa,2
5,6,5.4,3.9,1.7,0.4,Iris-setosa,2
6,7,4.6,3.4,1.4,0.3,Iris-setosa,2
7,8,5.0,3.4,1.5,0.2,Iris-setosa,2
8,9,4.4,2.9,1.4,0.2,Iris-setosa,2
9,10,4.9,3.1,1.5,0.1,Iris-setosa,2
10,11,5.4,3.7,1.5,0.2,Iris-setosa,2
11,12,4.8,3.4,1.6,0.2,Iris-setosa,2
12,13,4.8,3.0,1.4,0.1,Iris-setosa,2
13,14,4.3,3.0,1.1,0.1,Iris-setosa,2
14,15,5.8,4.0,1.2,0.2,Iris-setosa,2
15,16,5.7,4.4,1.5,0.4,Iris-setosa,2
16,17,5.4,3.9,1.3,0.4,Iris-setosa,2
17,18,5.1,3.5,1.4,0.3,Iris-setosa,2
18,19,5.7,3.8,1.7,0.3,Iris-setosa,2
19,20,5.1,3.8,1.5,0.3,Iris-setosa,2
20,21,5.4,3.4,1.7,0.2,Iris-setosa,2
21,22,5.1,3.7,1.5,0.4,Iris-setosa,2
22,23,4.6,3.6,1.0,0.2,Iris-setosa,2
23,24,5.1,3.3,1.7,0.5,Iris-setosa,2
24,25,4.8,3.4,1.9,0.2,Iris-setosa,2
25,26,5.0,3.0,1.6,0.2,Iris-setosa,2
26,27,5.0,3.4,1.6,0.4,Iris-setosa,2
27,28,5.2,3.5,1.5,0.2,Iris-setosa,2
28,29,5.2,3.4,1.4,0.2,Iris-setosa,2
29,30,4.7,3.2,1.6,0.2,Iris-setosa,2
30,31,4.8,3.1,1.6,0.2,Iris-setosa,2
31,32,5.4,3.4,1.5,0.4,Iris-setosa,2
32,33,5.2,4.1,1.5,0.1,Iris-setosa,2
33,34,5.5,4.2,1.4,0.2,Iris-setosa,2
34,35,4.9,3.1,1.5,0.1,Iris-setosa,2
35,36,5.0,3.2,1.2,0.2,Iris-setosa,2
36,37,5.5,3.5,1.3,0.2,Iris-setosa,2
37,38,4.9,3.1,1.5,0.1,Iris-setosa,2
38,39,4.4,3.0,1.3,0.2,Iris-setosa,2
39,40,5.1,3.4,1.5,0.2,Iris-setosa,2
40,41,5.0,3.5,1.3,0.3,Iris-setosa,2
41,42,4.5,2.3,1.3,0.3,Iris-setosa,2
42,43,4.4,3.2,1.3,0.2,Iris-setosa,2
43,44,5.0,3.5,1.6,0.6,Iris-setosa,2
44,45,5.1,3.8,1.9,0.4,Iris-setosa,2
45,46,4.8,3.0,1.4,0.3,Iris-setosa,2
46,47,5.1,3.8,1.6,0.2,Iris-setosa,2
47,48,4.6,3.2,1.4,0.2,Iris-setosa,2
48,49,5.3,3.7,1.5,0.2,Iris-setosa,2
49,50,5.0,3.3,1.4,0.2,Iris-setosa,2

In [44]:
data.kmeans.replace({0: "Iris-versicolor",
                   1: "Iris-virginica",
                   2: "Iris-setosa"}, inplace=True)

In [45]:
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,kmeans
0,1,5.1,3.5,1.4,0.2,Iris-setosa,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa,Iris-setosa
...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica,Iris-versicolor
147,148,6.5,3.0,5.2,2.0,Iris-virginica,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica,Iris-versicolor

In [46]:
data["hc_cluster"] = hc_cluster

In [53]:
data[data["hc_cluster"] == 2]

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,kmeans,hc_cluster
41,42,4.5,2.3,1.3,0.3,Iris-setosa,Iris-setosa,2
53,54,5.5,2.3,4.0,1.3,Iris-versicolor,Iris-versicolor,2
55,56,5.7,2.8,4.5,1.3,Iris-versicolor,Iris-versicolor,2
57,58,4.9,2.4,3.3,1.0,Iris-versicolor,Iris-versicolor,2
59,60,5.2,2.7,3.9,1.4,Iris-versicolor,Iris-versicolor,2
60,61,5.0,2.0,3.5,1.0,Iris-versicolor,Iris-versicolor,2
62,63,6.0,2.2,4.0,1.0,Iris-versicolor,Iris-versicolor,2
64,65,5.6,2.9,3.6,1.3,Iris-versicolor,Iris-versicolor,2
66,67,5.6,3.0,4.5,1.5,Iris-versicolor,Iris-versicolor,2
67,68,5.8,2.7,4.1,1.0,Iris-versicolor,Iris-versicolor,2
68,69,6.2,2.2,4.5,1.5,Iris-versicolor,Iris-versicolor,2
69,70,5.6,2.5,3.9,1.1,Iris-versicolor,Iris-versicolor,2
79,80,5.7,2.6,3.5,1.0,Iris-versicolor,Iris-versicolor,2
80,81,5.5,2.4,3.8,1.1,Iris-versicolor,Iris-versicolor,2
81,82,5.5,2.4,3.7,1.0,Iris-versicolor,Iris-versicolor,2
82,83,5.8,2.7,3.9,1.2,Iris-versicolor,Iris-versicolor,2
84,85,5.4,3.0,4.5,1.5,Iris-versicolor,Iris-versicolor,2
87,88,6.3,2.3,4.4,1.3,Iris-versicolor,Iris-versicolor,2
88,89,5.6,3.0,4.1,1.3,Iris-versicolor,Iris-versicolor,2
89,90,5.5,2.5,4.0,1.3,Iris-versicolor,Iris-versicolor,2
90,91,5.5,2.6,4.4,1.2,Iris-versicolor,Iris-versicolor,2
92,93,5.8,2.6,4.0,1.2,Iris-versicolor,Iris-versicolor,2
93,94,5.0,2.3,3.3,1.0,Iris-versicolor,Iris-versicolor,2
94,95,5.6,2.7,4.2,1.3,Iris-versicolor,Iris-versicolor,2
95,96,5.7,3.0,4.2,1.2,Iris-versicolor,Iris-versicolor,2
96,97,5.7,2.9,4.2,1.3,Iris-versicolor,Iris-versicolor,2
98,99,5.1,2.5,3.0,1.1,Iris-versicolor,Iris-versicolor,2
99,100,5.7,2.8,4.1,1.3,Iris-versicolor,Iris-versicolor,2
106,107,4.9,2.5,4.5,1.7,Iris-virginica,Iris-versicolor,2
119,120,6.0,2.2,5.0,1.5,Iris-virginica,Iris-versicolor,2

In [54]:
data.hc_cluster.replace({0: "Iris-virginica",
                   1: "Iris-setosa",
                   2: "Iris-versicolor"}, inplace=True)

In [55]:
data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species,kmeans,hc_cluster
0,1,5.1,3.5,1.4,0.2,Iris-setosa,Iris-setosa,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa,Iris-setosa,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa,Iris-setosa,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa,Iris-setosa,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa,Iris-setosa,Iris-setosa
...,...,...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica,Iris-virginica,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica,Iris-versicolor,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica,Iris-virginica,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica,Iris-virginica,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica,Iris-versicolor,Iris-virginica

In [56]:
data.Species.value_counts()

Iris-versicolor    50
Iris-virginica     50
Iris-setosa        50
Name: Species, dtype: int64

In [57]:
data.kmeans.value_counts()

Iris-versicolor    53
Iris-setosa        50
Iris-virginica     47
Name: kmeans, dtype: int64

In [58]:
data.hc_cluster.value_counts()

Iris-virginica     71
Iris-setosa        49
Iris-versicolor    30
Name: hc_cluster, dtype: int64